### PR TITLE
Authentication

### PR DESCRIPTION
**Pull request by tareq89**

### CODE REVIEW

**Comment by thehoneymad** [comment]
h4. Review.
1. Services are supposed to be shared. It's better if we have that with account.service.ts but as in TaskCat /token endpoint is not a part of account, that's okay. 
2. I dont see proper error handling to let the user know whether they are wrong or right about their username and password. You can create a new ticket to work on it or fix it here.

**Comment by tareq89** [comment]
Creating a new ticket to fix the error handling!

**Comment by thehoneymad** [comment]
You can refactor and reuse the control-message component if you want

**Comment by thehoneymad** [comment]
Im closing this pull request without a merge, I would merge the branch back to #32 and then merge back to master with the localStorage works missing here.

**Pull request closed without merging**
